### ISSUE TITLE
[bug] Application does not start in 1.4.2 version and higher

### ISSUE THREAD

**Issue by bialas1993** [Rijul-Ahuja/Xposed-Knock-Code#14]
I have Nexus 4 with android 6.0.1.
Version 1.4.1 works well, but doesn't have polish translate.

**Comment by Rijul-Ahuja** [comment]
No log is no fix

**Comment by Rijul-Ahuja** [comment]
Hey, can you please take logs using adb logcat or provide Xposed log? I have no idea what the issue is or how to fix it, because it works on my OPX with CM 13.0 without any issues.

**Comment by Rijul-Ahuja** [comment]
Does this description match your symptoms?
http://forum.xda-developers.com/showpost.php?p=69383296&postcount=666

**Comment by Rijul-Ahuja** [comment]
Also, did you switch to PIN (v1.4.2 replaces PIN instead of pattern now)

**Comment by bialas1993** [comment]
Ok, it work when I switch to PIN pattern
