### ISSUE TITLE
HTC support for directly show password entry

### ISSUE THREAD

**Issue by Rijul-Ahuja** [Rijul-Ahuja/Xposed-Knock-Code#20]
As reported by @Maxr1998, trying to fix this https://github.com/Rijul-Ahuja/Xposed-Knock-Code/blob/master/app/src/main/java/me/rijul/knockcode/XposedMod.java#L126

A temporary fix would just be to catch the ClassNotFoundException, but it would disable the resulting hook, and therefore the feature via this line https://github.com/Rijul-Ahuja/Xposed-Knock-Code/blob/master/app/src/main/java/me/rijul/knockcode/XposedMod.java#L379

Currently considering whether a different hook (in the `handleLoadPackage` method) will work, will upload a test version here to obtain feedback.

**Comment by Rijul-Ahuja** [comment]
@Maxr1998, please try this version and report back https://github.com/Rijul-Ahuja/Xposed-Knock-Code/blob/master/app-release_htc.apk?raw=true

**Comment by Maxr1998** [comment]
@Rijul-Ahuja works perfectly now, thank you very much!! :D
Had to disable "Simple PIN" (aka PIN with length of 4) though, as it'd say that PIN isn't configured then.
